name: Registry Management

on:
  workflow_run:
    workflows: ["Bundle and Deploy"]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  registry-update:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event in same repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: registry-management
          client-payload: >-
            {"repository":"${{ github.event.workflow_run.repository.full_name }}",
             "branch":"${{ github.event.workflow_run.head_branch }}"}
